package com.edu.PiJEE;
// Generated 17 nov. 2016 21:49:43 by Hibernate Tools 4.3.1.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Alert generated by hbm2java
 */
@Entity
@Table(name = "alert", catalog = "room")
public class Alert implements java.io.Serializable {

	private Integer alertId;
	private User user;
	private String titre12;
	private String region12;
	private Integer nbrDeBinom12;
	private Integer price12;
	private Date startDate;
	private int startPoint;
	private int endPoint;
	private String critere;

	public Alert() {
	}

	public Alert(Date startDate, int startPoint, int endPoint) {
		this.startDate = startDate;
		this.startPoint = startPoint;
		this.endPoint = endPoint;
	}

	public Alert(User user, String titre12, String region12, Integer nbrDeBinom12, Integer price12, Date startDate,
			int startPoint, int endPoint, String critere) {
		this.user = user;
		this.titre12 = titre12;
		this.region12 = region12;
		this.nbrDeBinom12 = nbrDeBinom12;
		this.price12 = price12;
		this.startDate = startDate;
		this.startPoint = startPoint;
		this.endPoint = endPoint;
		this.critere = critere;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "AlertId", unique = true, nullable = false)
	public Integer getAlertId() {
		return this.alertId;
	}

	public void setAlertId(Integer alertId) {
		this.alertId = alertId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "iduser")
	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	@Column(name = "Titre12")
	public String getTitre12() {
		return this.titre12;
	}

	public void setTitre12(String titre12) {
		this.titre12 = titre12;
	}

	@Column(name = "Region12")
	public String getRegion12() {
		return this.region12;
	}

	public void setRegion12(String region12) {
		this.region12 = region12;
	}

	@Column(name = "nbr_de_binom12")
	public Integer getNbrDeBinom12() {
		return this.nbrDeBinom12;
	}

	public void setNbrDeBinom12(Integer nbrDeBinom12) {
		this.nbrDeBinom12 = nbrDeBinom12;
	}

	@Column(name = "Price12")
	public Integer getPrice12() {
		return this.price12;
	}

	public void setPrice12(Integer price12) {
		this.price12 = price12;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "StartDate", nullable = false, length = 19)
	public Date getStartDate() {
		return this.startDate;
	}

	public void setStartDate(Date startDate) {
		this.startDate = startDate;
	}

	@Column(name = "StartPoint", nullable = false)
	public int getStartPoint() {
		return this.startPoint;
	}

	public void setStartPoint(int startPoint) {
		this.startPoint = startPoint;
	}

	@Column(name = "EndPoint", nullable = false)
	public int getEndPoint() {
		return this.endPoint;
	}

	public void setEndPoint(int endPoint) {
		this.endPoint = endPoint;
	}

	@Column(name = "critere")
	public String getCritere() {
		return this.critere;
	}

	public void setCritere(String critere) {
		this.critere = critere;
	}

}
