package com.edu.PiJEE;
// Generated 17 nov. 2016 21:49:43 by Hibernate Tools 4.3.1.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Aspnetuserlogins generated by hbm2java
 */
@Entity
@Table(name = "aspnetuserlogins", catalog = "room")
public class Aspnetuserlogins implements java.io.Serializable {

	private AspnetuserloginsId id;
	private User user;

	public Aspnetuserlogins() {
	}

	public Aspnetuserlogins(AspnetuserloginsId id, User user) {
		this.id = id;
		this.user = user;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "loginProvider", column = @Column(name = "LoginProvider", nullable = false, length = 128) ),
			@AttributeOverride(name = "providerKey", column = @Column(name = "ProviderKey", nullable = false, length = 128) ),
			@AttributeOverride(name = "userId", column = @Column(name = "UserId", nullable = false, length = 128) ) })
	public AspnetuserloginsId getId() {
		return this.id;
	}

	public void setId(AspnetuserloginsId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "UserId", nullable = false, insertable = false, updatable = false)
	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

}
