package com.edu.PiJEE;
// Generated 17 nov. 2016 21:49:43 by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;

import java.util.List;

import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Discution generated by hbm2java
 */
@Entity
@Table(name = "discution", catalog = "room")
public class Discution implements java.io.Serializable {

	private Integer discutionGroupId;
	private Groupcollocation groupcollocation;
	private User user;
	private String titre;
	private String text;

	private  List<Comment> comments;

	public Discution() {
	}
    @OneToMany(mappedBy="discution")
	public List<Comment> getComments() {
		return comments;
	}

	public void setComments(List<Comment> comments) {
		this.comments = comments;
	}

	public Discution(Groupcollocation groupcollocation) {
		this.groupcollocation = groupcollocation;
	}

	public Discution(Groupcollocation groupcollocation, User user, String titre, String text) {
		this.groupcollocation = groupcollocation;
		this.user = user;
		this.titre = titre;
		this.text = text;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "DiscutionGroupId", unique = true, nullable = false)
	public Integer getDiscutionGroupId() {
		return this.discutionGroupId;
	}

	public void setDiscutionGroupId(Integer discutionGroupId) {
		this.discutionGroupId = discutionGroupId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CollocationGroupId", nullable = false)
	public Groupcollocation getGroupcollocation() {
		return this.groupcollocation;
	}

	public void setGroupcollocation(Groupcollocation groupcollocation) {
		this.groupcollocation = groupcollocation;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "UserIden")
	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	@Column(name = "Titre")
	public String getTitre() {
		return this.titre;
	}

	public void setTitre(String titre) {
		this.titre = titre;
	}

	@Column(name = "Text")
	public String getText() {
		return this.text;
	}

	public void setText(String text) {
		this.text = text;
	}

}
