package com.edu.PiJEE;
// Generated 17 nov. 2016 21:49:43 by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Aspnetroles generated by hbm2java
 */
@Entity
@Table(name = "aspnetroles", catalog = "room", uniqueConstraints = @UniqueConstraint(columnNames = "Name") )
public class Aspnetroles implements java.io.Serializable {

	private String id;
	private String name;
	private Set<User> users = new HashSet<User>(0);

	public Aspnetroles() {
	}

	public Aspnetroles(String id, String name) {
		this.id = id;
		this.name = name;
	}

	public Aspnetroles(String id, String name, Set<User> users) {
		this.id = id;
		this.name = name;
		this.users = users;
	}

	@Id

	@Column(name = "Id", unique = true, nullable = false, length = 128)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@Column(name = "Name", unique = true, nullable = false, length = 128)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "aspnetuserroles", catalog = "room", joinColumns = {
			@JoinColumn(name = "RoleId", nullable = false, updatable = false) }, inverseJoinColumns = {
					@JoinColumn(name = "UserId", nullable = false, updatable = false) })
	public Set<User> getUsers() {
		return this.users;
	}

	public void setUsers(Set<User> users) {
		this.users = users;
	}

}
