package com.edu.PiJEE;
// Generated 17 nov. 2016 21:49:43 by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * AspnetuserloginsId generated by hbm2java
 */
@Embeddable
public class AspnetuserloginsId implements java.io.Serializable {

	private String loginProvider;
	private String providerKey;
	private String userId;

	public AspnetuserloginsId() {
	}

	public AspnetuserloginsId(String loginProvider, String providerKey, String userId) {
		this.loginProvider = loginProvider;
		this.providerKey = providerKey;
		this.userId = userId;
	}

	@Column(name = "LoginProvider", nullable = false, length = 128)
	public String getLoginProvider() {
		return this.loginProvider;
	}

	public void setLoginProvider(String loginProvider) {
		this.loginProvider = loginProvider;
	}

	@Column(name = "ProviderKey", nullable = false, length = 128)
	public String getProviderKey() {
		return this.providerKey;
	}

	public void setProviderKey(String providerKey) {
		this.providerKey = providerKey;
	}

	@Column(name = "UserId", nullable = false, length = 128)
	public String getUserId() {
		return this.userId;
	}

	public void setUserId(String userId) {
		this.userId = userId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof AspnetuserloginsId))
			return false;
		AspnetuserloginsId castOther = (AspnetuserloginsId) other;

		return ((this.getLoginProvider() == castOther.getLoginProvider())
				|| (this.getLoginProvider() != null && castOther.getLoginProvider() != null
						&& this.getLoginProvider().equals(castOther.getLoginProvider())))
				&& ((this.getProviderKey() == castOther.getProviderKey())
						|| (this.getProviderKey() != null && castOther.getProviderKey() != null
								&& this.getProviderKey().equals(castOther.getProviderKey())))
				&& ((this.getUserId() == castOther.getUserId()) || (this.getUserId() != null
						&& castOther.getUserId() != null && this.getUserId().equals(castOther.getUserId())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getLoginProvider() == null ? 0 : this.getLoginProvider().hashCode());
		result = 37 * result + (getProviderKey() == null ? 0 : this.getProviderKey().hashCode());
		result = 37 * result + (getUserId() == null ? 0 : this.getUserId().hashCode());
		return result;
	}

}
