package com.edu.PiJEE;
// Generated 17 nov. 2016 21:49:43 by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Migrationhistory generated by hbm2java
 */
@Entity
@Table(name = "__migrationhistory", catalog = "room")
public class Migrationhistory implements java.io.Serializable {

	private String migrationId;
	private String contextKey;
	private byte[] model;
	private String productVersion;

	public Migrationhistory() {
	}

	public Migrationhistory(String migrationId, String contextKey, byte[] model, String productVersion) {
		this.migrationId = migrationId;
		this.contextKey = contextKey;
		this.model = model;
		this.productVersion = productVersion;
	}

	@Id

	@Column(name = "MigrationId", unique = true, nullable = false, length = 150)
	public String getMigrationId() {
		return this.migrationId;
	}

	public void setMigrationId(String migrationId) {
		this.migrationId = migrationId;
	}

	@Column(name = "ContextKey", nullable = false, length = 300)
	public String getContextKey() {
		return this.contextKey;
	}

	public void setContextKey(String contextKey) {
		this.contextKey = contextKey;
	}

	@Column(name = "Model", nullable = false)
	public byte[] getModel() {
		return this.model;
	}

	public void setModel(byte[] model) {
		this.model = model;
	}

	@Column(name = "ProductVersion", nullable = false, length = 32)
	public String getProductVersion() {
		return this.productVersion;
	}

	public void setProductVersion(String productVersion) {
		this.productVersion = productVersion;
	}

}
