package com.edu.PiJEE;
// Generated 17 nov. 2016 21:49:43 by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.Table;

/**
 * Trajet generated by hbm2java
 */
@Entity
@Table(name = "trajet", catalog = "room")
public class Trajet implements java.io.Serializable {

	private Integer trajetId;
	private String nomVille;
	private Set<Carpool> carpools = new HashSet<Carpool>(0);

	public Trajet() {
	}

	public Trajet(String nomVille, Set<Carpool> carpools) {
		this.nomVille = nomVille;
		this.carpools = carpools;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "TrajetId", unique = true, nullable = false)
	public Integer getTrajetId() {
		return this.trajetId;
	}

	public void setTrajetId(Integer trajetId) {
		this.trajetId = trajetId;
	}

	@Column(name = "NomVille")
	public String getNomVille() {
		return this.nomVille;
	}

	public void setNomVille(String nomVille) {
		this.nomVille = nomVille;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "carpool_trajet", catalog = "room", joinColumns = {
			@JoinColumn(name = "trajet_fk", nullable = false, updatable = false) }, inverseJoinColumns = {
					@JoinColumn(name = "carpool_fk", nullable = false, updatable = false) })
	public Set<Carpool> getCarpools() {
		return this.carpools;
	}

	public void setCarpools(Set<Carpool> carpools) {
		this.carpools = carpools;
	}

}
